language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pjamieso/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pjamieson/react-test npm test

after_success:
  - docker build -t pjamieson/multi-client ./client
  - docker build -t pjamieson/multi-nginx ./nginx
  - docker build -t pjamieson/multi-server ./server
  - docker build -t pjamieson/multi-worker ./worker
# must login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to Docker hub
  - docker push pjamieson/multi-client
  - docker push pjamieson/multi-nginx 
  - docker push pjamieson/multi-server 
  - docker push pjamieson/multi-worker
